### ISSUE TITLE
DIS7.xml RecordQueryReliablePdu value

### ISSUE THREAD

**Issue by camejia** [open-dis/open-dis-java#35] opened 2017-05-03 01:46 UTC
In the DIS7.xml file, RecordQueryReliablePdu is currently has value="63", but should have value="65".

I personally am not yet up to speed enough on the xmlpg and subsequent code patches to make this update...

**Comment by mcgredonps** [comment] 2017-05-03 16:21
Nicely spotted. Fixed in the actual XML repo I missed last night, at DISDescription here in the open-dis github project.

In the Java implementation it's somewhat dangerous to re-generate the source code, so I fixed that directly without a regeneration. There are various patches that can be made to the generated code when what the protocol does differs from the generation basics. That can be done as a Unix patch operation, but that's kinda unreliable.

**Comment by leif81** [comment] 2017-05-03 18:20
> In the Java implementation it's somewhat dangerous to re-generate the source code,

Don, I'm glad you said that! 

There's obviously a lot of effort saved by the code generator. However I too have been thinking about how painful it'd be if we were to regenerate the Java code at this point, given all the hand made improvements we've made :fearful: . The junit tests would be an alarm bell, they would either fail to compile or fail to pass. However it would still be a pretty large task to reapply the cumulative changes to get to a point where the tests pass again.

It sounds like you already agree, but maybe the best strategy is to use the code generator once for the initial library creation, and then from that point on just hand edit the source code like we are now?

**Comment by leif81** [comment] 2017-05-18 12:44
Fixed by @mcgredonps here

https://github.com/open-dis/DISDescription/commit/6bf1928e3123ae6232df9d7c1316f66d84350394

**Closed by leif81** 2017-05-18 12:44 UTC

**Comment by mcgredonps** [comment] 2017-05-18 16:59
The link that shows up on the page at open-dis-java is now DISDescription @ 6ff1b08<https://github.com/open-dis/DISDescription/tree/6ff1b0889dcf6053cf654f07f4773ff67ae48109> ;
is it the case that the open-dis-java link is going to the most recent version at DISDescription,
or is that going to an older, un-updated version? I thought if I just fixed the content at the
DISDescription repo it would automatically be updated at for example open-dis-java.


On May 18, 2017, at 5:44 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed by @mcgredonps<https://github.com/mcgredonps> here

open-dis/DISDescription@6bf1928<https://github.com/open-dis/DISDescription/commit/6bf1928e3123ae6232df9d7c1316f66d84350394>

**Comment by leif81** [comment] 2017-05-18 18:43
git submodules are a bit funny. The `DISDescription` submodule in `open-dis-java` won't automatically point at the latest commit because it's actually locked to an earlier commit (by design). It would need to be updated manually. This is both a blessing and a curse! I personally limit my use of submodules these days because of the headaches they've caused me!

**Comment by mcgredonps** [comment] 2017-05-18 21:38
Huh. Interesting, but I suppose you can make the argument that pointing
at another repo is always going to be pointing at  a specific version, rather than
whatever is latest. In contrast to the ancient stuff in the SVN world, where you
just pointed it at the latest.

Now I gotta run through any other languages and make sure they point at
the latest.


On May 18, 2017, at 11:43 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


git submodules are a bit funny. The DISDescription submodule in open-dis-java won't automatically point at the latest commit because it's actually locked to an earlier commit (by design). It would need to be updated manually. This is both a blessing and a curse! I personally limit my use of submodules these days because of the headaches they've caused me!
